### ISSUE TITLE
Continually getting the same error

### ISSUE THREAD

**Issue by pelargir** [heroku/heroku-accounts#12]
Installed the plugin and added an account. No errors. As soon as I run `heroku accounts` I get this:

```
Cannot read property 'login' of undefined
```

And I get that same error for anything else I run. I can't switch accounts, I can't list accounts. Always get the same error. I tried uninstalling and reinstalling the CLI but that did not help.

Both Heroku accounts I'm using have two-factor auth enabled. That's the only thing I can think of that might be interfering. Does this plugin support two-factor auth?

**Comment by tillleinen** [comment]
@pelargir I had the same problem, have a look at #9: You have to select an account before you can list them

**Comment by pelargir** [comment]
@tillleinen thanks so much! That trick worked. Sure is unexpected behavior.
