### ISSUE TITLE
Running `heroku plugins:install heroku-accounts` throughs a 404 error

### ISSUE THREAD

**Issue by mobilutz** [heroku/heroku-accounts#18]
Running the command with `--verbose` showed me this error:
```
verbose 1.108 Performing "GET" request to "http://cli-npm.heroku.com/semver/-/semver-5.5.1/7dfdd8814bdb7cabc7be0fb1d734cfb66c940477.tgz".
verbose 1.163 Error: http://cli-npm.heroku.com/semver/-/semver-5.5.1/7dfdd8814bdb7cabc7be0fb1d734cfb66c940477.tgz: Request failed "404 Not Found"
```

Is seems that some content is not there anymore ...

**Comment by leonardfactory** [comment]
Running `heroku update` (or your [recommended update method](https://devcenter.heroku.com/articles/heroku-cli#troubleshooting)) solved the issue for me

**Comment by mobilutz** [comment]
Just ran the command again, and now it works.
It looks like the fail that was missing is back!
