### ISSUE TITLE
Heroku account not switching based on app directory

### ISSUE THREAD

**Issue by imme5150** [heroku/heroku-accounts#3]
I previously used https://github.com/ddollar/heroku-accounts/ without any problems.  When I changed into the directory of the project I was working on, it would switch to the correct account for that app.  I believe it used `git config heroku.account` to determine which account to use.

how do I enable this functionality again?  I switch back and forth between different projects under different accounts all day.

currently using `heroku accounts:set` sets the heroku account to use globally.

**Comment by dickeyxxx** [comment]
Plugins will no longer be able to monkey patch all the commands of the CLI. While this was useful for things like this plugin, it had a very high maintenance cost and was the source of many bugs. For this reason, we won't be supporting it with the new CLI. The old plugin is now incompatible with `heroku run` as well as the http-git remotes which is the default now.

**Comment by imme5150** [comment]
How can I set up heroku to use a different account for each app?  This is a key feature for me as I have different accounts for each of my client's apps.

**Comment by jacobbullock** [comment]
would love to be able to set a project root to use a specific account.  sounds like the only option currently is to manually switch accounts?

**Comment by rikkipitt** [comment]
I asked a question over at https://github.com/ddollar/heroku-accounts/issues/80 about creating a plugin for ZSH to enable us to see which Heroku account was currently logged into (a bit like how viewing a Git project can prompt us what branch we're on for example).

What I came up with is this:

<img width="466" alt="screen shot 2015-10-05 at 23 01 39" src="https://cloud.githubusercontent.com/assets/1147871/10295016/91353b78-6bb5-11e5-9b57-1f46f9e02deb.png">

However, it's not too efficient as it occasionally hangs after a period of inactivity. I tried a variety of ways to ask for the currently logged in account, but all seem to do an "auth" which has to ping Heroku. Not too bad for now and I use it on a daily basis to alleviate help the above issue when managing several accounts.

I'll try and see if I can release this if anyone is interested in helping me develop it further... Let me know.

Rikki

**Comment by dickeyxxx** [comment]
This is not possible with http-git as far as I know.

**Comment by imme5150** [comment]
What about using SSH Keys?

**Comment by dickeyxxx** [comment]
While it's possible with ssh keys, we're now recommend http-git and there isn't a way for a plugin to modify the current account for all commands anymore.

**Comment by imme5150** [comment]
Well there should be a way to set this up.  It was working great for me before and like I said I use this every day.  I love heroku and I've been using it for years, but it's not cool to force me to change something that was working fine w/o a replacement.

**Comment by dickeyxxx** [comment]
I do apologize but as I described earlier, this was the source of many issues and we made the decision not to support it.

**Comment by imme5150** [comment]
I already have a script that sets up my local environment for each of my projects, so I'll probably add a line to the script to set my credentials to match the project.  Might also add some aliases like `hap` which will set me back to my personal account.  That should suffice for me, but I'm disappointed.

**Comment by dickeyxxx** [comment]
For what it's worth, I'm going to have a conversation with the product team about this to see what we can do to make the experience better with multiple accounts. Also, Github issues pretty much just goes to me. A better way to ask for different functionality would be to submit a support ticket addressed to the product team.

**Comment by mokolabs** [comment]
Hey, @dickeyxxx. Any update on this issue?

This was a critical feature of the previous plugin that really helped Heroku users with lots of apps and accounts. (You guys want lots of users with lots of apps, right? ;)

In my case, the Heroku toolbelt just updated itself, removed the deprecated plugin, and all of my apps just broke -- without warning. That was not a good experience and I'm sure that Heroku can do better.

Like others, I'll probably try to rig up something to auto-switch accounts for now, but I would love to see this feature restored.
