### ISSUE TITLE
 `accounts:current` is not a heroku command.

### ISSUE THREAD

**Issue by thekcsam** [heroku/heroku-accounts#4]
Other command is working perfectly fine, but only `accounts:current` throw me this error.

**Comment by ransombriggs** [comment]
@samkahchiin could you please post in the error output?

**Comment by thekcsam** [comment]
@ransombriggs , this is the error output I got.

`heroku accounts:current`

```
 !    `accounts:current` is not a heroku command.
 !    See `heroku help` for a list of available commands.
```

**Comment by dickeyxxx** [comment]
that command is not part of this plugin

**Comment by jdx** [comment]
what is the output of `heroku version`?

**Comment by seonixx** [comment]
+1 for this issue.
heroku-toolbelt/3.43.13 (x86_64-darwin10.8.0) ruby/1.9.3
heroku-cli/5.4.8-eee5ec9 (darwin-amd64) go1.7.1

**Comment by jdx** [comment]
it wasn't released, I just pushed it
