### ISSUE TITLE
Default account

### ISSUE THREAD

**Issue by chrise86** [heroku/heroku-accounts#5]
`heroku accounts:default personal` no longer seems to work:

    `accounts:default` is not a heroku command.

**Comment by dickeyxxx** [comment]
This plugin is really just an account switcher. The "default" account is just the one you are on.

**Comment by chrise86** [comment]
The ddollar/heroku-accounts version had this functionality, and by default I mean the one that gets used automatically without specifying an account. For instance, I just created a new directory, then a new Heroku app, and it was created under my work account rather than personal. It would be useful to specify the "default" behaviour.

**Comment by dickeyxxx** [comment]
This one does not change based on directory, so running `accounts:set` will change the default (only) acccount.
