### ISSUE TITLE
Wondering if this plugin is not usable anymore? Cannot set multiple accounts?

### ISSUE THREAD

**Issue by thomasjoyce** [heroku/heroku-accounts#6]
Hi,

   I realize that i cannot set multiple account anymore. previously it was working.
After reading this issue: https://github.com/heroku/heroku-accounts/issues/3
i looks like heroku-account is not usable anymore.
Is that right? If it is, it would be best to have set some sort of description the state of this project? 

Any ideal suggestion on what heroku team is planning to have for multiple account settings? 
Thanks for the info :- )

**Comment by dickeyxxx** [comment]
it works, it's just not possible to have it automatically switch directories

**Comment by thomasjoyce** [comment]
i believe that is the main feature of the plugin...to be able to switch
multiple accounts in heroku easily.
By not having that, what is the usefulness of this plugin?

**Comment by dickeyxxx** [comment]
this plugin allows you to switch accounts without having to login again
