### ISSUE TITLE
No longer supports configuring an account per project via .git/config

### ISSUE THREAD

**Issue by rmm5t** [heroku/heroku-accounts#8]
This fork no longer supports configuring an account per project in the `.git/config` of the project like the original version by @ddollar did.

Any likelihood that if I worked on a pull-request to re-enable this behavior, it might get pulled in?

For example, if a project's `.git/config` contained the following, this plugin would automatically switch to the "myaccount" account.

```
[heroku]
  account = myaccount
```

Reference to original: https://github.com/ddollar/heroku-accounts/blob/master/lib/accounts/heroku/auth.rb#L19

**Comment by dickeyxxx** [comment]
this is no longer possible with http git but you're welcome to fork this plugin if you only use ssh git with heroku

**Comment by rmm5t** [comment]
@dickeyxxx It's true that I use ssh git everywhere, but sorry, I don’t understand how http vs ssh git is related to this feature request.

The config is only used to look up the account name to be used. What am I misunderstanding?

**Comment by dickeyxxx** [comment]
`git push` isn't going to work with http git and multiple accounts

**Comment by dickeyxxx** [comment]
also you should be aware that most of the code is moving to node plugins that won't support any of the monkey patching required to make this plugin function the way it was before

**Comment by rmm5t** [comment]
> `git push` isn't going to work with http git and multiple accounts

Sorry, I'm feeling dumb right now, but what does `git push` have to do with using features in the heroku toolbelt?  I don't use the heroku toolbelt for any of my git pushes?  I do use the `--remote` option with an ssh git url, but that's unrelated to setting the current auth settings for a particular heroku account (that's managed by this plugin).

All I'm looking for is a way to effectively reconfigure my current heroku account using an _**account name**_ on a per project basis.  The equivalent of this would be running `heroku accounts:set myaccount` when I chdir into a project directory.

> also you should be aware that most of the code is moving to node plugins that won't support any of the monkey patching required to make this plugin function the way it was before

That's good to know.

**Comment by dickeyxxx** [comment]
If you use `git push heroku master` it won't necessarily be the same account that you have setup with `heroku-accounts`.

That's not the bigger issue though, the bigger issue is that this is a ruby plugin but all the commands are moving over to node code that doesn't allow for plugins to perform monkey patching. For example, this plugin wouldn't be able to work in that way for `heroku run`.

**Comment by rmm5t** [comment]
> If you use git push heroku master it won't necessarily be the same account that you have setup with heroku-accounts.

I see. I guess because I only use ssh git, I didn't realize that this plugin would also manage `git push` against http git. I assumed it would only power the heroku-toolbelt features. 

> That's not the bigger issue though, the bigger issue is that this is a ruby plugin but all the commands are moving over to node code that doesn't allow for plugins to perform monkey patching. For example, this plugin wouldn't be able to work in that way for heroku run.

Point taken.
